// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZrlygVs-lGbSUf19-jruVfrNBidi1vG0',
    appId: '1:573902408662:web:48aace779872c3123e7277',
    messagingSenderId: '573902408662',
    projectId: 'nextstop-demo',
    authDomain: 'nextstop-demo.firebaseapp.com',
    storageBucket: 'nextstop-demo.firebasestorage.app',
    measurementId: 'G-LY7CWCB5J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-WuGdMj19subvjjtFqRQ1X5o0itJ3cbY',
    appId: '1:573902408662:android:ed2d0add10deed263e7277',
    messagingSenderId: '573902408662',
    projectId: 'nextstop-demo',
    storageBucket: 'nextstop-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw4sDTdy5UAL8zh6vGwCrZEQyx67bgWes',
    appId: '1:573902408662:ios:9aa2f0a187f40f703e7277',
    messagingSenderId: '573902408662',
    projectId: 'nextstop-demo',
    storageBucket: 'nextstop-demo.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw4sDTdy5UAL8zh6vGwCrZEQyx67bgWes',
    appId: '1:573902408662:ios:9aa2f0a187f40f703e7277',
    messagingSenderId: '573902408662',
    projectId: 'nextstop-demo',
    storageBucket: 'nextstop-demo.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZrlygVs-lGbSUf19-jruVfrNBidi1vG0',
    appId: '1:573902408662:web:7ce54d74d178cf0e3e7277',
    messagingSenderId: '573902408662',
    projectId: 'nextstop-demo',
    authDomain: 'nextstop-demo.firebaseapp.com',
    storageBucket: 'nextstop-demo.firebasestorage.app',
    measurementId: 'G-PEPMNRCZ7X',
  );
}
